version: "3"

networks:
  internet:
    external: true
  # kvm_net:
    # external: true
    # name: kvm_net

services:
  webvirtcloud:
    image: "muratovas/webvirtcloud"
    container_name: webvirtcloud
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/libvirt/:/var/run/libvirt/
      - /dev/pts/:/dev/pts/
      # - ./data:/srv/webvirtcloud/data
      # - ./ssh:/var/www/.ssh
      # - ./webvirtcloud:/srv/webvirtcloud/webvirtcloud
    environment:
      KVM_HOST: "172.24.0.1"
    networks:
      internet:
      # kvm_net:

  # nginx:
    # image: weejewel/nginx-with-certbot
    # container_name: nginx
    # restart: unless-stopped
    # ports:
      # - "80:80"
      # - "443:443"
    # networks:
      # - internet
    # volumes:
      # #- ./nginx/servers/:/etc/nginx/servers/
      # #- ./nginx/auth/:/etc/nginx/auth/
      # - ./nginx/.htpasswd:/etc/nginx/auth/.htpasswd
      # - ./nginx/servers.conf:/etc/nginx/servers/servers.conf
      # - ./nginx/certificate/:/etc/nginx/certificate
      # - ./nginx/letsencrypt/:/etc/letsencrypt/
